version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api/src:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app
    ports:
      - "5001:5001"
    command: ["npm", "run", "dev"]